name: Trigger auto deployment for container-app-sample

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-sample-AutoDeployTrigger-f9592e1e-9d15-4236-90db-8a0f848e3493.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca7de4627a83acr.azurecr.io
          username: ${{ secrets.CONTAINERAPPSAMPLE_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPSAMPLE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca7de4627a83acr.azurecr.io/container-app-sample:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPSAMPLE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-sample -g snehapar-test --server ca7de4627a83acr.azurecr.io --username  ${{ secrets.CONTAINERAPPSAMPLE_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPSAMPLE_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-sample -g snehapar-test --image ca7de4627a83acr.azurecr.io/container-app-sample:${{ github.sha }}
