name: Trigger auto deployment for sample-test-1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sample-test-1-AutoDeployTrigger-68b08f31-353d-4d66-aef3-2c959007ac84.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SAMPLETEST1_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.SAMPLETEST1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SAMPLETEST1_REGISTRY_PASSWORD }}
          containerAppName: sample-test-1
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/sample-test-1:${{ github.sha }}
          

     

