name: Trigger auto deployment for sample-test-1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sample-test-1-AutoDeployTrigger-938a5582-8d86-4ee8-98c2-8d25d89626ac.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SAMPLETEST1_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.SAMPLETEST1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SAMPLETEST1_REGISTRY_PASSWORD }}
          containerAppName: sample-test-1
          resourceGroup: ca-snehapar-group
          imageToBuild: jollymeadow-a493d675.eastus.azurecontainerapps-test.io/privateregistry:${{ github.sha }}
          

     

